//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicallCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryHot
    {
        public int id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string login { get; set; }
        public string name { get; set; }
        public Nullable<int> role { get; set; }
        public string block { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
